pipelines:
  branches:
    master:
      - step:
          script:
            - pipe: atlassian/azure-web-apps-deploy:1.0.1
                az login
              variables:
                AZURE_APP_ID: i393839@fhict.nl
                AZURE_PASSWORD: Dependencyinversion1
                AZURE_TENANT_ID: 0172c9f5-f568-42ac-9eb8-24ef84881faa
                AZURE_RESOURCE_GROUP: 'Mediaan-Digital-Menu'
                AZURE_APP_NAME: 'qr-service1'
                ZIP_FILE: 'app.zip'
